version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - dprint
  - evalue
  - gcode
  - PETG
  - Pronterface
  - pydantic
  - pytest
  - setuptools
  - typer
ignoreWords: []
import: []
